id: P006627
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016299
  title: གསུང་འབུམ། དྲི་མེད་འོད་ཟེར། ༼སྡེ་དགེ་པར་མ།༽
  author: ''
  volumes:
    df443ff10f11496499795060f97c9943:
      image_group_id: I1CZ5001
      title: ''
      volume_number: 1
      total_pages: 1140
    57f22724e8ce47869419a8dc332077e6:
      image_group_id: I1CZ5002
      title: ''
      volume_number: 2
      total_pages: 1266
      base_file: v001.txt
    b98ceaceb22a43ada253ff8b1ff20ebe:
      image_group_id: I1CZ5003
      title: ''
      volume_number: 3
      total_pages: 1136
      base_file: v002.txt
    51997b5ca73c4d90b205d69c5290fa44:
      image_group_id: I1CZ5004
      title: ''
      volume_number: 4
      total_pages: 1276
      base_file: v003.txt
    c68e7da3d27d45afb9515fc0b2d0e554:
      image_group_id: I1CZ5005
      title: ''
      volume_number: 5
      total_pages: 928
      base_file: v004.txt
